# Generated by Django 5.1.6 on 2025-03-04 11:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_name_post_image_filter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_post_o0lbny', max_length=255, verbose_name='image'),
        ),
    ]
